Running zerver.tests.test_auth_backends.AppleAuthBackendNativeFlowTest.test_config_error_development
Running zerver.tests.test_auth_backends.AppleAuthBackendNativeFlowTest.test_config_error_production
Running zerver.tests.test_auth_backends.AppleAuthBackendNativeFlowTest.test_id_token_with_invalid_aud_sent
Running zerver.tests.test_auth_backends.AppleAuthBackendNativeFlowTest.test_no_id_token_sent
Running zerver.tests.test_auth_backends.AppleAuthBackendNativeFlowTest.test_social_auth_complete
2020-07-17 06:16:37.279 INFO [zulip.auth.apple] AuthFailed: Authentication failed: 
2020-07-17 06:16:37.327 INFO [zulip.auth.apple] HTTPError: 
Running zerver.tests.test_auth_backends.AppleAuthBackendNativeFlowTest.test_social_auth_complete_when_base_exc_is_raised
Running zerver.tests.test_auth_backends.AppleAuthBackendNativeFlowTest.test_social_auth_deactivated_user
Running zerver.tests.test_auth_backends.AppleAuthBackendNativeFlowTest.test_social_auth_desktop_registration
Running zerver.tests.test_auth_backends.AppleAuthBackendNativeFlowTest.test_social_auth_desktop_success
Running zerver.tests.test_auth_backends.AppleAuthBackendNativeFlowTest.test_social_auth_invalid_email
2020-07-17 06:16:38.233 WARN [zulip.auth.apple] Apple got invalid email argument.
Running zerver.tests.test_auth_backends.AppleAuthBackendNativeFlowTest.test_social_auth_invalid_realm
Running zerver.tests.test_auth_backends.AppleAuthBackendNativeFlowTest.test_social_auth_invited_as_admin_but_expired
Running zerver.tests.test_auth_backends.AppleAuthBackendNativeFlowTest.test_social_auth_mobile_and_desktop_flow_in_one_request_error
Running zerver.tests.test_auth_backends.AppleAuthBackendNativeFlowTest.test_social_auth_mobile_registration
Running zerver.tests.test_auth_backends.AppleAuthBackendNativeFlowTest.test_social_auth_mobile_success
Running zerver.tests.test_auth_backends.AppleAuthBackendNativeFlowTest.test_social_auth_no_key
Running zerver.tests.test_auth_backends.AppleAuthBackendNativeFlowTest.test_social_auth_registration
Running zerver.tests.test_auth_backends.AppleAuthBackendNativeFlowTest.test_social_auth_registration_existing_account
Running zerver.tests.test_auth_backends.AppleAuthBackendNativeFlowTest.test_social_auth_registration_invitation_exists
Running zerver.tests.test_auth_backends.AppleAuthBackendNativeFlowTest.test_social_auth_registration_using_multiuse_invite
Running zerver.tests.test_auth_backends.AppleAuthBackendNativeFlowTest.test_social_auth_registration_without_is_signup
Running zerver.tests.test_auth_backends.AppleAuthBackendNativeFlowTest.test_social_auth_registration_without_is_signup_closed_realm
Running zerver.tests.test_auth_backends.AppleAuthBackendNativeFlowTest.test_social_auth_session_fields_cleared_correctly
2020-07-17 06:16:40.532 INFO [] /complete/apple/: Authentication failed: Token validation failed
2020-07-17 06:16:40.547 INFO [] /complete/apple/: Authentication failed: Token validation failed
Running zerver.tests.test_auth_backends.AppleAuthBackendNativeFlowTest.test_social_auth_success
Running zerver.tests.test_auth_backends.AppleAuthBackendNativeFlowTest.test_social_auth_with_ldap_auth_registration_from_confirmation
2020-07-17 06:16:40.711 WARN [] New account email alice@zulip.com could not be found in LDAP
2020-07-17 06:16:40.719 DEBG [zulip.ldap] ZulipLDAPAuthBackend: No ldap user matching django_to_ldap_username result: alice@zulip.com. Input username: alice@zulip.com
Running zerver.tests.test_auth_backends.AppleAuthBackendNativeFlowTest.test_social_auth_with_ldap_populate_registration_from_confirmation
2020-07-17 06:16:41.277 WARN [] New account email alice@zulip.com could not be found in LDAP
Running zerver.tests.test_auth_backends.AppleAuthBackendNativeFlowTest.test_user_cannot_log_into_nonexisting_realm
Running zerver.tests.test_auth_backends.AppleAuthBackendNativeFlowTest.test_user_cannot_log_into_wrong_subdomain
Running zerver.tests.test_auth_backends.AppleAuthBackendNativeFlowTest.test_when_social_auth_subdomain_is_not_set
Running zerver.tests.test_auth_backends.AppleIdAuthBackendTest.test_apple_auth_enabled
Running zerver.tests.test_auth_backends.AppleIdAuthBackendTest.test_auth_registration_with_no_name_sent_from_apple
Running zerver.tests.test_auth_backends.AppleIdAuthBackendTest.test_config_error_development
Running zerver.tests.test_auth_backends.AppleIdAuthBackendTest.test_config_error_production
Running zerver.tests.test_auth_backends.AppleIdAuthBackendTest.test_id_token_verification_failure
Running zerver.tests.test_auth_backends.AppleIdAuthBackendTest.test_social_auth_complete
2020-07-17 06:16:42.175 INFO [zulip.auth.apple] AuthFailed: Authentication failed: 
2020-07-17 06:16:42.184 INFO [zulip.auth.apple] HTTPError: 
Running zerver.tests.test_auth_backends.AppleIdAuthBackendTest.test_social_auth_complete_when_base_exc_is_raised
Running zerver.tests.test_auth_backends.AppleIdAuthBackendTest.test_social_auth_deactivated_user
Running zerver.tests.test_auth_backends.AppleIdAuthBackendTest.test_social_auth_desktop_registration
Running zerver.tests.test_auth_backends.AppleIdAuthBackendTest.test_social_auth_desktop_success
Running zerver.tests.test_auth_backends.AppleIdAuthBackendTest.test_social_auth_invalid_email
2020-07-17 06:16:42.845 WARN [zulip.auth.apple] Apple got invalid email argument.
Running zerver.tests.test_auth_backends.AppleIdAuthBackendTest.test_social_auth_invalid_realm
Running zerver.tests.test_auth_backends.AppleIdAuthBackendTest.test_social_auth_invited_as_admin_but_expired
Running zerver.tests.test_auth_backends.AppleIdAuthBackendTest.test_social_auth_mobile_and_desktop_flow_in_one_request_error
Running zerver.tests.test_auth_backends.AppleIdAuthBackendTest.test_social_auth_mobile_registration
Running zerver.tests.test_auth_backends.AppleIdAuthBackendTest.test_social_auth_mobile_success
Running zerver.tests.test_auth_backends.AppleIdAuthBackendTest.test_social_auth_no_key
Running zerver.tests.test_auth_backends.AppleIdAuthBackendTest.test_social_auth_registration
Running zerver.tests.test_auth_backends.AppleIdAuthBackendTest.test_social_auth_registration_existing_account
Running zerver.tests.test_auth_backends.AppleIdAuthBackendTest.test_social_auth_registration_invitation_exists
Running zerver.tests.test_auth_backends.AppleIdAuthBackendTest.test_social_auth_registration_using_multiuse_invite
Running zerver.tests.test_auth_backends.AppleIdAuthBackendTest.test_social_auth_registration_without_is_signup
Running zerver.tests.test_auth_backends.AppleIdAuthBackendTest.test_social_auth_registration_without_is_signup_closed_realm
Running zerver.tests.test_auth_backends.AppleIdAuthBackendTest.test_social_auth_session_fields_cleared_correctly
Running zerver.tests.test_auth_backends.AppleIdAuthBackendTest.test_social_auth_success
Running zerver.tests.test_auth_backends.AppleIdAuthBackendTest.test_social_auth_with_ldap_auth_registration_from_confirmation
2020-07-17 06:16:45.477 WARN [] New account email alice@zulip.com could not be found in LDAP
2020-07-17 06:16:45.486 DEBG [zulip.ldap] ZulipLDAPAuthBackend: No ldap user matching django_to_ldap_username result: alice@zulip.com. Input username: alice@zulip.com
Running zerver.tests.test_auth_backends.AppleIdAuthBackendTest.test_social_auth_with_ldap_populate_registration_from_confirmation
2020-07-17 06:16:46.106 WARN [] New account email alice@zulip.com could not be found in LDAP
Running zerver.tests.test_auth_backends.AppleIdAuthBackendTest.test_user_cannot_log_into_nonexisting_realm
Running zerver.tests.test_auth_backends.AppleIdAuthBackendTest.test_user_cannot_log_into_wrong_subdomain
Running zerver.tests.test_auth_backends.AppleIdAuthBackendTest.test_validate_state
Running zerver.tests.test_auth_backends.AppleIdAuthBackendTest.test_when_social_auth_subdomain_is_not_set
Running zerver.tests.test_auth_backends.AuthBackendTest.test_any_backend_enabled
Running zerver.tests.test_auth_backends.AuthBackendTest.test_devauth_backend
Running zerver.tests.test_auth_backends.AuthBackendTest.test_dummy_backend
Running zerver.tests.test_auth_backends.AuthBackendTest.test_email_auth_backend
Running zerver.tests.test_auth_backends.AuthBackendTest.test_email_auth_backend_disabled_password_auth
Running zerver.tests.test_auth_backends.AuthBackendTest.test_email_auth_backend_empty_password
Running zerver.tests.test_auth_backends.AuthBackendTest.test_ldap_backend
Running zerver.tests.test_auth_backends.AuthBackendTest.test_login_preview
Running zerver.tests.test_auth_backends.AuthBackendTest.test_no_backend_enabled
Running zerver.tests.test_auth_backends.AuthBackendTest.test_remote_user_backend
Running zerver.tests.test_auth_backends.AuthBackendTest.test_remote_user_backend_invalid_realm
Running zerver.tests.test_auth_backends.AuthBackendTest.test_remote_user_backend_sso_append_domain
Running zerver.tests.test_auth_backends.AuthBackendTest.test_social_auth_backends
2020-07-17 06:16:48.942 INFO [zulip.auth.google] Failed login attempt for deactivated account: 10@zulip
2020-07-17 06:16:49.033 INFO [zulip.auth.google] Failed login attempt for deactivated account: 10@zulip
2020-07-17 06:16:49.126 INFO [zulip.auth.github] Failed login attempt for deactivated account: 10@zulip
2020-07-17 06:16:49.223 INFO [zulip.auth.github] Failed login attempt for deactivated account: 10@zulip
Running zerver.tests.test_auth_backends.CheckPasswordStrengthTest.test_check_password_strength
Running zerver.tests.test_auth_backends.DevFetchAPIKeyTest.test_deactivated_realm
Running zerver.tests.test_auth_backends.DevFetchAPIKeyTest.test_dev_auth_disabled
Running zerver.tests.test_auth_backends.DevFetchAPIKeyTest.test_inactive_user
Running zerver.tests.test_auth_backends.DevFetchAPIKeyTest.test_invalid_email
Running zerver.tests.test_auth_backends.DevFetchAPIKeyTest.test_success
Running zerver.tests.test_auth_backends.DevFetchAPIKeyTest.test_unregistered_user
Running zerver.tests.test_auth_backends.DevGetEmailsTest.test_dev_auth_disabled
Running zerver.tests.test_auth_backends.DevGetEmailsTest.test_success
Running zerver.tests.test_auth_backends.DjangoToLDAPUsernameTests.test_authenticate_to_ldap_via_email
Running zerver.tests.test_auth_backends.DjangoToLDAPUsernameTests.test_django_to_ldap_username_with_append_domain
Running zerver.tests.test_auth_backends.DjangoToLDAPUsernameTests.test_django_to_ldap_username_with_email_search
Running zerver.tests.test_auth_backends.DjangoToLDAPUsernameTests.test_sync_user_from_ldap_with_email_attr
Running zerver.tests.test_auth_backends.EmailValidatorTestCase.test_invalid_email
Running zerver.tests.test_auth_backends.EmailValidatorTestCase.test_valid_email
Running zerver.tests.test_auth_backends.EmailValidatorTestCase.test_validate_email
Running zerver.tests.test_auth_backends.ExternalMethodDictsTests.test_get_external_method_buttons
Running zerver.tests.test_auth_backends.ExternalMethodDictsTests.test_get_external_method_dicts_correctly_sorted
Running zerver.tests.test_auth_backends.ExternalMethodDictsTests.test_get_external_method_dicts_multiple_saml_idps
Running zerver.tests.test_auth_backends.FetchAPIKeyTest.test_deactivated_realm
Running zerver.tests.test_auth_backends.FetchAPIKeyTest.test_inactive_user
Running zerver.tests.test_auth_backends.FetchAPIKeyTest.test_invalid_email
Running zerver.tests.test_auth_backends.FetchAPIKeyTest.test_ldap_auth_email_auth_disabled_success
Running zerver.tests.test_auth_backends.FetchAPIKeyTest.test_password_auth_disabled
Running zerver.tests.test_auth_backends.FetchAPIKeyTest.test_success
Running zerver.tests.test_auth_backends.FetchAPIKeyTest.test_wrong_password
Running zerver.tests.test_auth_backends.FetchAuthBackends.test_get_server_settings
Running zerver.tests.test_auth_backends.GitHubAuthBackendTest.test_config_error_development
Running zerver.tests.test_auth_backends.GitHubAuthBackendTest.test_config_error_production
Running zerver.tests.test_auth_backends.GitHubAuthBackendTest.test_github_auth_enabled
Running zerver.tests.test_auth_backends.GitHubAuthBackendTest.test_github_oauth2_email_no_reply_dot_github_dot_com
Running zerver.tests.test_auth_backends.GitHubAuthBackendTest.test_github_oauth2_email_not_associated
Running zerver.tests.test_auth_backends.GitHubAuthBackendTest.test_github_oauth2_login_multiple_accounts_exist
Running zerver.tests.test_auth_backends.GitHubAuthBackendTest.test_github_oauth2_login_no_account_exists
Running zerver.tests.test_auth_backends.GitHubAuthBackendTest.test_github_oauth2_login_only_one_account_exists
Running zerver.tests.test_auth_backends.GitHubAuthBackendTest.test_github_oauth2_signup_choose_existing_account
Running zerver.tests.test_auth_backends.GitHubAuthBackendTest.test_github_oauth2_signup_choose_new_email_to_register
Running zerver.tests.test_auth_backends.GitHubAuthBackendTest.test_github_oauth2_success_non_primary
Running zerver.tests.test_auth_backends.GitHubAuthBackendTest.test_github_oauth2_success_single_email
Running zerver.tests.test_auth_backends.GitHubAuthBackendTest.test_github_unverified_email_with_existing_account
Running zerver.tests.test_auth_backends.GitHubAuthBackendTest.test_social_auth_complete
2020-07-17 06:16:50.841 INFO [zulip.auth.github] AuthFailed: Authentication failed: 
2020-07-17 06:16:50.845 INFO [zulip.auth.github] HTTPError: 
Running zerver.tests.test_auth_backends.GitHubAuthBackendTest.test_social_auth_complete_when_base_exc_is_raised
Running zerver.tests.test_auth_backends.GitHubAuthBackendTest.test_social_auth_deactivated_user
Running zerver.tests.test_auth_backends.GitHubAuthBackendTest.test_social_auth_desktop_registration
Running zerver.tests.test_auth_backends.GitHubAuthBackendTest.test_social_auth_desktop_success
Running zerver.tests.test_auth_backends.GitHubAuthBackendTest.test_social_auth_email_not_verified
Running zerver.tests.test_auth_backends.GitHubAuthBackendTest.test_social_auth_github_organization_member_success
Running zerver.tests.test_auth_backends.GitHubAuthBackendTest.test_social_auth_github_organization_not_member_failed
Running zerver.tests.test_auth_backends.GitHubAuthBackendTest.test_social_auth_github_team_member_success
Running zerver.tests.test_auth_backends.GitHubAuthBackendTest.test_social_auth_github_team_not_member_failed
Running zerver.tests.test_auth_backends.GitHubAuthBackendTest.test_social_auth_invalid_email
2020-07-17 06:16:51.444 WARN [zulip.auth.github] GitHub got invalid email argument.
Running zerver.tests.test_auth_backends.GitHubAuthBackendTest.test_social_auth_invalid_realm
Running zerver.tests.test_auth_backends.GitHubAuthBackendTest.test_social_auth_invited_as_admin_but_expired
Running zerver.tests.test_auth_backends.GitHubAuthBackendTest.test_social_auth_mobile_and_desktop_flow_in_one_request_error
Running zerver.tests.test_auth_backends.GitHubAuthBackendTest.test_social_auth_mobile_registration
Running zerver.tests.test_auth_backends.GitHubAuthBackendTest.test_social_auth_mobile_success
Running zerver.tests.test_auth_backends.GitHubAuthBackendTest.test_social_auth_no_key
Running zerver.tests.test_auth_backends.GitHubAuthBackendTest.test_social_auth_registration
Running zerver.tests.test_auth_backends.GitHubAuthBackendTest.test_social_auth_registration_existing_account
Running zerver.tests.test_auth_backends.GitHubAuthBackendTest.test_social_auth_registration_invitation_exists
Running zerver.tests.test_auth_backends.GitHubAuthBackendTest.test_social_auth_registration_using_multiuse_invite
Running zerver.tests.test_auth_backends.GitHubAuthBackendTest.test_social_auth_registration_without_is_signup
Running zerver.tests.test_auth_backends.GitHubAuthBackendTest.test_social_auth_registration_without_is_signup_closed_realm
Running zerver.tests.test_auth_backends.GitHubAuthBackendTest.test_social_auth_session_fields_cleared_correctly
Running zerver.tests.test_auth_backends.GitHubAuthBackendTest.test_social_auth_success
Running zerver.tests.test_auth_backends.GitHubAuthBackendTest.test_social_auth_with_ldap_auth_registration_from_confirmation
2020-07-17 06:16:53.155 WARN [] New account email alice@zulip.com could not be found in LDAP
2020-07-17 06:16:53.176 DEBG [zulip.ldap] ZulipLDAPAuthBackend: No ldap user matching django_to_ldap_username result: alice@zulip.com. Input username: alice@zulip.com
Running zerver.tests.test_auth_backends.GitHubAuthBackendTest.test_social_auth_with_ldap_populate_registration_from_confirmation
2020-07-17 06:16:53.533 WARN [] New account email alice@zulip.com could not be found in LDAP
Running zerver.tests.test_auth_backends.GitHubAuthBackendTest.test_user_cannot_log_into_nonexisting_realm
Running zerver.tests.test_auth_backends.GitHubAuthBackendTest.test_user_cannot_log_into_wrong_subdomain
Running zerver.tests.test_auth_backends.GitHubAuthBackendTest.test_when_social_auth_subdomain_is_not_set
Running zerver.tests.test_auth_backends.GitLabAuthBackendTest.test_config_error_development
Running zerver.tests.test_auth_backends.GitLabAuthBackendTest.test_config_error_production
Running zerver.tests.test_auth_backends.GitLabAuthBackendTest.test_gitlab_auth_enabled
Running zerver.tests.test_auth_backends.GitLabAuthBackendTest.test_social_auth_complete
2020-07-17 06:16:53.830 INFO [zulip.auth.gitlab] AuthFailed: Authentication failed: 
2020-07-17 06:16:53.834 INFO [zulip.auth.gitlab] HTTPError: 
Running zerver.tests.test_auth_backends.GitLabAuthBackendTest.test_social_auth_complete_when_base_exc_is_raised
Running zerver.tests.test_auth_backends.GitLabAuthBackendTest.test_social_auth_deactivated_user
Running zerver.tests.test_auth_backends.GitLabAuthBackendTest.test_social_auth_desktop_registration
Running zerver.tests.test_auth_backends.GitLabAuthBackendTest.test_social_auth_desktop_success
Running zerver.tests.test_auth_backends.GitLabAuthBackendTest.test_social_auth_invalid_email
2020-07-17 06:16:54.229 WARN [zulip.auth.gitlab] GitLab got invalid email argument.
Running zerver.tests.test_auth_backends.GitLabAuthBackendTest.test_social_auth_invalid_realm
Running zerver.tests.test_auth_backends.GitLabAuthBackendTest.test_social_auth_invited_as_admin_but_expired
Running zerver.tests.test_auth_backends.GitLabAuthBackendTest.test_social_auth_mobile_and_desktop_flow_in_one_request_error
Running zerver.tests.test_auth_backends.GitLabAuthBackendTest.test_social_auth_mobile_registration
Running zerver.tests.test_auth_backends.GitLabAuthBackendTest.test_social_auth_mobile_success
Running zerver.tests.test_auth_backends.GitLabAuthBackendTest.test_social_auth_no_key
Running zerver.tests.test_auth_backends.GitLabAuthBackendTest.test_social_auth_registration
Running zerver.tests.test_auth_backends.GitLabAuthBackendTest.test_social_auth_registration_existing_account
Running zerver.tests.test_auth_backends.GitLabAuthBackendTest.test_social_auth_registration_invitation_exists
Running zerver.tests.test_auth_backends.GitLabAuthBackendTest.test_social_auth_registration_using_multiuse_invite
Running zerver.tests.test_auth_backends.GitLabAuthBackendTest.test_social_auth_registration_without_is_signup
Running zerver.tests.test_auth_backends.GitLabAuthBackendTest.test_social_auth_registration_without_is_signup_closed_realm
Running zerver.tests.test_auth_backends.GitLabAuthBackendTest.test_social_auth_session_fields_cleared_correctly
Running zerver.tests.test_auth_backends.GitLabAuthBackendTest.test_social_auth_success
Running zerver.tests.test_auth_backends.GitLabAuthBackendTest.test_social_auth_with_ldap_auth_registration_from_confirmation
2020-07-17 06:16:55.733 WARN [] New account email alice@zulip.com could not be found in LDAP
2020-07-17 06:16:55.754 DEBG [zulip.ldap] ZulipLDAPAuthBackend: No ldap user matching django_to_ldap_username result: alice@zulip.com. Input username: alice@zulip.com
Running zerver.tests.test_auth_backends.GitLabAuthBackendTest.test_social_auth_with_ldap_populate_registration_from_confirmation
2020-07-17 06:16:56.068 WARN [] New account email alice@zulip.com could not be found in LDAP
Running zerver.tests.test_auth_backends.GitLabAuthBackendTest.test_user_cannot_log_into_nonexisting_realm
Running zerver.tests.test_auth_backends.GitLabAuthBackendTest.test_user_cannot_log_into_wrong_subdomain
Running zerver.tests.test_auth_backends.GitLabAuthBackendTest.test_when_social_auth_subdomain_is_not_set
Running zerver.tests.test_auth_backends.GoogleAuthBackendTest.test_config_error_development
Running zerver.tests.test_auth_backends.GoogleAuthBackendTest.test_config_error_production
Running zerver.tests.test_auth_backends.GoogleAuthBackendTest.test_google_auth_enabled
Running zerver.tests.test_auth_backends.GoogleAuthBackendTest.test_log_into_subdomain_when_email_is_none
Running zerver.tests.test_auth_backends.GoogleAuthBackendTest.test_log_into_subdomain_when_is_signup_is_false_and_new_user
Running zerver.tests.test_auth_backends.GoogleAuthBackendTest.test_log_into_subdomain_when_is_signup_is_true_and_new_user
Running zerver.tests.test_auth_backends.GoogleAuthBackendTest.test_log_into_subdomain_when_token_is_malformed
Running zerver.tests.test_auth_backends.GoogleAuthBackendTest.test_log_into_subdomain_when_token_not_found
Running zerver.tests.test_auth_backends.GoogleAuthBackendTest.test_log_into_subdomain_when_using_invite_link
Running zerver.tests.test_auth_backends.GoogleAuthBackendTest.test_prevent_duplicate_signups
Running zerver.tests.test_auth_backends.GoogleAuthBackendTest.test_redirect_to_next_url_for_log_into_subdomain
Running zerver.tests.test_auth_backends.GoogleAuthBackendTest.test_social_auth_complete
2020-07-17 06:16:56.847 INFO [zulip.auth.google] AuthFailed: Authentication failed: 
2020-07-17 06:16:56.851 INFO [zulip.auth.google] HTTPError: 
Running zerver.tests.test_auth_backends.GoogleAuthBackendTest.test_social_auth_complete_when_base_exc_is_raised
Running zerver.tests.test_auth_backends.GoogleAuthBackendTest.test_social_auth_deactivated_user
Running zerver.tests.test_auth_backends.GoogleAuthBackendTest.test_social_auth_desktop_registration
Running zerver.tests.test_auth_backends.GoogleAuthBackendTest.test_social_auth_desktop_success
Running zerver.tests.test_auth_backends.GoogleAuthBackendTest.test_social_auth_email_not_verified
Running zerver.tests.test_auth_backends.GoogleAuthBackendTest.test_social_auth_invalid_email
2020-07-17 06:16:57.219 WARN [zulip.auth.google] Google got invalid email argument.
Running zerver.tests.test_auth_backends.GoogleAuthBackendTest.test_social_auth_invalid_realm
Running zerver.tests.test_auth_backends.GoogleAuthBackendTest.test_social_auth_invited_as_admin_but_expired
Running zerver.tests.test_auth_backends.GoogleAuthBackendTest.test_social_auth_mobile_and_desktop_flow_in_one_request_error
Running zerver.tests.test_auth_backends.GoogleAuthBackendTest.test_social_auth_mobile_realm_uri
Running zerver.tests.test_auth_backends.GoogleAuthBackendTest.test_social_auth_mobile_registration
Running zerver.tests.test_auth_backends.GoogleAuthBackendTest.test_social_auth_mobile_success
Running zerver.tests.test_auth_backends.GoogleAuthBackendTest.test_social_auth_mobile_success_legacy_url
Running zerver.tests.test_auth_backends.GoogleAuthBackendTest.test_social_auth_no_key
Running zerver.tests.test_auth_backends.GoogleAuthBackendTest.test_social_auth_registration
Running zerver.tests.test_auth_backends.GoogleAuthBackendTest.test_social_auth_registration_existing_account
Running zerver.tests.test_auth_backends.GoogleAuthBackendTest.test_social_auth_registration_invitation_exists
Running zerver.tests.test_auth_backends.GoogleAuthBackendTest.test_social_auth_registration_using_multiuse_invite
Running zerver.tests.test_auth_backends.GoogleAuthBackendTest.test_social_auth_registration_without_is_signup
Running zerver.tests.test_auth_backends.GoogleAuthBackendTest.test_social_auth_registration_without_is_signup_closed_realm
Running zerver.tests.test_auth_backends.GoogleAuthBackendTest.test_social_auth_session_fields_cleared_correctly
Running zerver.tests.test_auth_backends.GoogleAuthBackendTest.test_social_auth_success
Running zerver.tests.test_auth_backends.GoogleAuthBackendTest.test_social_auth_with_ldap_auth_registration_from_confirmation
2020-07-17 06:16:58.771 WARN [] New account email alice@zulip.com could not be found in LDAP
2020-07-17 06:16:58.795 DEBG [zulip.ldap] ZulipLDAPAuthBackend: No ldap user matching django_to_ldap_username result: alice@zulip.com. Input username: alice@zulip.com
Running zerver.tests.test_auth_backends.GoogleAuthBackendTest.test_social_auth_with_ldap_populate_registration_from_confirmation
2020-07-17 06:16:59.116 WARN [] New account email alice@zulip.com could not be found in LDAP
Running zerver.tests.test_auth_backends.GoogleAuthBackendTest.test_user_cannot_log_into_nonexisting_realm
Running zerver.tests.test_auth_backends.GoogleAuthBackendTest.test_user_cannot_log_into_wrong_subdomain
Running zerver.tests.test_auth_backends.GoogleAuthBackendTest.test_when_social_auth_subdomain_is_not_set
Running zerver.tests.test_auth_backends.JSONFetchAPIKeyTest.test_not_loggedin
Running zerver.tests.test_auth_backends.JSONFetchAPIKeyTest.test_success
Running zerver.tests.test_auth_backends.JSONFetchAPIKeyTest.test_wrong_password
Running zerver.tests.test_auth_backends.LDAPBackendTest.test_non_existing_realm
2020-07-17 06:16:59.389 WARN [django_auth_ldap] ('Realm is None', 1) while authenticating hamlet
Running zerver.tests.test_auth_backends.RateLimitAuthenticationTests.test_email_and_ldap_backends_user_based_rate_limiting
Running zerver.tests.test_auth_backends.RateLimitAuthenticationTests.test_email_auth_backend_user_based_rate_limiting
Running zerver.tests.test_auth_backends.RateLimitAuthenticationTests.test_ldap_backend_user_based_rate_limiting
Running zerver.tests.test_auth_backends.SAMLAuthBackendTest.test_choose_subdomain_invalid_subdomain_specified
Running zerver.tests.test_auth_backends.SAMLAuthBackendTest.test_config_error_development
Running zerver.tests.test_auth_backends.SAMLAuthBackendTest.test_config_error_page
2020-07-17 06:16:59.635 INFO [] Attempted to initiate SAML authentication with wrong idp argument: None
Running zerver.tests.test_auth_backends.SAMLAuthBackendTest.test_config_error_production
Running zerver.tests.test_auth_backends.SAMLAuthBackendTest.test_idp_initiated_signin_subdomain_implicit
Running zerver.tests.test_auth_backends.SAMLAuthBackendTest.test_idp_initiated_signin_subdomain_implicit_invalid
Running zerver.tests.test_auth_backends.SAMLAuthBackendTest.test_idp_initiated_signin_subdomain_implicit_no_relaystate_param
Running zerver.tests.test_auth_backends.SAMLAuthBackendTest.test_idp_initiated_signin_subdomain_specified
Running zerver.tests.test_auth_backends.SAMLAuthBackendTest.test_saml_auth_enabled
Running zerver.tests.test_auth_backends.SAMLAuthBackendTest.test_saml_auth_works_without_private_public_keys
Running zerver.tests.test_auth_backends.SAMLAuthBackendTest.test_social_auth_complete
Running zerver.tests.test_auth_backends.SAMLAuthBackendTest.test_social_auth_complete_bad_params
Running zerver.tests.test_auth_backends.SAMLAuthBackendTest.test_social_auth_complete_no_subdomain
Running zerver.tests.test_auth_backends.SAMLAuthBackendTest.test_social_auth_complete_valid_get_idp_bad_samlresponse
Running zerver.tests.test_auth_backends.SAMLAuthBackendTest.test_social_auth_complete_when_base_exc_is_raised
Running zerver.tests.test_auth_backends.SAMLAuthBackendTest.test_social_auth_complete_wrong_issuing_idp
Running zerver.tests.test_auth_backends.SAMLAuthBackendTest.test_social_auth_deactivated_user
Running zerver.tests.test_auth_backends.SAMLAuthBackendTest.test_social_auth_desktop_registration
Running zerver.tests.test_auth_backends.SAMLAuthBackendTest.test_social_auth_desktop_success
Running zerver.tests.test_auth_backends.SAMLAuthBackendTest.test_social_auth_invalid_email
2020-07-17 06:17:00.358 WARN [zulip.auth.saml] SAML got invalid email argument.
Running zerver.tests.test_auth_backends.SAMLAuthBackendTest.test_social_auth_invalid_realm
Running zerver.tests.test_auth_backends.SAMLAuthBackendTest.test_social_auth_invited_as_admin_but_expired
Running zerver.tests.test_auth_backends.SAMLAuthBackendTest.test_social_auth_mobile_and_desktop_flow_in_one_request_error
Running zerver.tests.test_auth_backends.SAMLAuthBackendTest.test_social_auth_mobile_registration
Running zerver.tests.test_auth_backends.SAMLAuthBackendTest.test_social_auth_mobile_success
Running zerver.tests.test_auth_backends.SAMLAuthBackendTest.test_social_auth_no_key
Running zerver.tests.test_auth_backends.SAMLAuthBackendTest.test_social_auth_registration
Running zerver.tests.test_auth_backends.SAMLAuthBackendTest.test_social_auth_registration_existing_account
Running zerver.tests.test_auth_backends.SAMLAuthBackendTest.test_social_auth_registration_invitation_exists
Running zerver.tests.test_auth_backends.SAMLAuthBackendTest.test_social_auth_registration_using_multiuse_invite
Running zerver.tests.test_auth_backends.SAMLAuthBackendTest.test_social_auth_registration_without_is_signup
Running zerver.tests.test_auth_backends.SAMLAuthBackendTest.test_social_auth_registration_without_is_signup_closed_realm
Running zerver.tests.test_auth_backends.SAMLAuthBackendTest.test_social_auth_saml_bad_idp_param_on_login_page
Running zerver.tests.test_auth_backends.SAMLAuthBackendTest.test_social_auth_saml_idp_limited_to_subdomains_attempt_wrong_realm
Running zerver.tests.test_auth_backends.SAMLAuthBackendTest.test_social_auth_saml_idp_limited_to_subdomains_success
Running zerver.tests.test_auth_backends.SAMLAuthBackendTest.test_social_auth_saml_idp_org_membership_failed
Running zerver.tests.test_auth_backends.SAMLAuthBackendTest.test_social_auth_saml_idp_org_membership_root_subdomain
Running zerver.tests.test_auth_backends.SAMLAuthBackendTest.test_social_auth_saml_idp_org_membership_success
Running zerver.tests.test_auth_backends.SAMLAuthBackendTest.test_social_auth_saml_login_bad_idp_arg
2020-07-17 06:17:02.071 INFO [] Attempted to initiate SAML authentication with wrong idp argument: None
2020-07-17 06:17:02.074 INFO [] Attempted to initiate SAML authentication with wrong idp argument: nonexistent_idp
2020-07-17 06:17:02.088 INFO [] Attempted to initiate SAML authentication with wrong idp argument: None
2020-07-17 06:17:02.091 INFO [] Attempted to initiate SAML authentication with wrong idp argument: nonexistent_idp
Running zerver.tests.test_auth_backends.SAMLAuthBackendTest.test_social_auth_saml_multiple_idps_configured
Running zerver.tests.test_auth_backends.SAMLAuthBackendTest.test_social_auth_saml_require_limit_to_subdomains
Running zerver.tests.test_auth_backends.SAMLAuthBackendTest.test_social_auth_session_fields_cleared_correctly
Running zerver.tests.test_auth_backends.SAMLAuthBackendTest.test_social_auth_success
Running zerver.tests.test_auth_backends.SAMLAuthBackendTest.test_social_auth_with_ldap_auth_registration_from_confirmation
2020-07-17 06:17:02.367 WARN [] New account email alice@zulip.com could not be found in LDAP
2020-07-17 06:17:02.372 DEBG [zulip.ldap] ZulipLDAPAuthBackend: No ldap user matching django_to_ldap_username result: alice@zulip.com. Input username: alice@zulip.com
Running zerver.tests.test_auth_backends.SAMLAuthBackendTest.test_social_auth_with_ldap_populate_registration_from_confirmation
2020-07-17 06:17:02.723 WARN [] New account email alice@zulip.com could not be found in LDAP
Running zerver.tests.test_auth_backends.SAMLAuthBackendTest.test_user_cannot_log_into_nonexisting_realm
Running zerver.tests.test_auth_backends.SAMLAuthBackendTest.test_user_cannot_log_into_wrong_subdomain
Running zerver.tests.test_auth_backends.SAMLAuthBackendTest.test_when_social_auth_subdomain_is_not_set
Running zerver.tests.test_auth_backends.SocialAuthBase.test_config_error_development
** Skipping zerver.tests.test_auth_backends.SocialAuthBase.test_config_error_development: 
Running zerver.tests.test_auth_backends.SocialAuthBase.test_config_error_production
** Skipping zerver.tests.test_auth_backends.SocialAuthBase.test_config_error_production: 
Running zerver.tests.test_auth_backends.SocialAuthBase.test_social_auth_complete
** Skipping zerver.tests.test_auth_backends.SocialAuthBase.test_social_auth_complete: 
Running zerver.tests.test_auth_backends.SocialAuthBase.test_social_auth_complete_when_base_exc_is_raised
** Skipping zerver.tests.test_auth_backends.SocialAuthBase.test_social_auth_complete_when_base_exc_is_raised: 
Running zerver.tests.test_auth_backends.SocialAuthBase.test_social_auth_deactivated_user
** Skipping zerver.tests.test_auth_backends.SocialAuthBase.test_social_auth_deactivated_user: 
Running zerver.tests.test_auth_backends.SocialAuthBase.test_social_auth_desktop_registration
** Skipping zerver.tests.test_auth_backends.SocialAuthBase.test_social_auth_desktop_registration: 
Running zerver.tests.test_auth_backends.SocialAuthBase.test_social_auth_desktop_success
** Skipping zerver.tests.test_auth_backends.SocialAuthBase.test_social_auth_desktop_success: 
Running zerver.tests.test_auth_backends.SocialAuthBase.test_social_auth_invalid_email
** Skipping zerver.tests.test_auth_backends.SocialAuthBase.test_social_auth_invalid_email: 
Running zerver.tests.test_auth_backends.SocialAuthBase.test_social_auth_invalid_realm
** Skipping zerver.tests.test_auth_backends.SocialAuthBase.test_social_auth_invalid_realm: 
Running zerver.tests.test_auth_backends.SocialAuthBase.test_social_auth_invited_as_admin_but_expired
** Skipping zerver.tests.test_auth_backends.SocialAuthBase.test_social_auth_invited_as_admin_but_expired: 
Running zerver.tests.test_auth_backends.SocialAuthBase.test_social_auth_mobile_and_desktop_flow_in_one_request_error
** Skipping zerver.tests.test_auth_backends.SocialAuthBase.test_social_auth_mobile_and_desktop_flow_in_one_request_error: 
Running zerver.tests.test_auth_backends.SocialAuthBase.test_social_auth_mobile_registration
** Skipping zerver.tests.test_auth_backends.SocialAuthBase.test_social_auth_mobile_registration: 
Running zerver.tests.test_auth_backends.SocialAuthBase.test_social_auth_mobile_success
** Skipping zerver.tests.test_auth_backends.SocialAuthBase.test_social_auth_mobile_success: 
Running zerver.tests.test_auth_backends.SocialAuthBase.test_social_auth_no_key
** Skipping zerver.tests.test_auth_backends.SocialAuthBase.test_social_auth_no_key: 
Running zerver.tests.test_auth_backends.SocialAuthBase.test_social_auth_registration
** Skipping zerver.tests.test_auth_backends.SocialAuthBase.test_social_auth_registration: 
Running zerver.tests.test_auth_backends.SocialAuthBase.test_social_auth_registration_existing_account
** Skipping zerver.tests.test_auth_backends.SocialAuthBase.test_social_auth_registration_existing_account: 
Running zerver.tests.test_auth_backends.SocialAuthBase.test_social_auth_registration_invitation_exists
** Skipping zerver.tests.test_auth_backends.SocialAuthBase.test_social_auth_registration_invitation_exists: 
Running zerver.tests.test_auth_backends.SocialAuthBase.test_social_auth_registration_using_multiuse_invite
** Skipping zerver.tests.test_auth_backends.SocialAuthBase.test_social_auth_registration_using_multiuse_invite: 
Running zerver.tests.test_auth_backends.SocialAuthBase.test_social_auth_registration_without_is_signup
** Skipping zerver.tests.test_auth_backends.SocialAuthBase.test_social_auth_registration_without_is_signup: 
Running zerver.tests.test_auth_backends.SocialAuthBase.test_social_auth_registration_without_is_signup_closed_realm
** Skipping zerver.tests.test_auth_backends.SocialAuthBase.test_social_auth_registration_without_is_signup_closed_realm: 
Running zerver.tests.test_auth_backends.SocialAuthBase.test_social_auth_session_fields_cleared_correctly
** Skipping zerver.tests.test_auth_backends.SocialAuthBase.test_social_auth_session_fields_cleared_correctly: 
Running zerver.tests.test_auth_backends.SocialAuthBase.test_social_auth_success
** Skipping zerver.tests.test_auth_backends.SocialAuthBase.test_social_auth_success: 
Running zerver.tests.test_auth_backends.SocialAuthBase.test_social_auth_with_ldap_auth_registration_from_confirmation
** Skipping zerver.tests.test_auth_backends.SocialAuthBase.test_social_auth_with_ldap_auth_registration_from_confirmation: 
Running zerver.tests.test_auth_backends.SocialAuthBase.test_social_auth_with_ldap_populate_registration_from_confirmation
** Skipping zerver.tests.test_auth_backends.SocialAuthBase.test_social_auth_with_ldap_populate_registration_from_confirmation: 
Running zerver.tests.test_auth_backends.SocialAuthBase.test_user_cannot_log_into_nonexisting_realm
** Skipping zerver.tests.test_auth_backends.SocialAuthBase.test_user_cannot_log_into_nonexisting_realm: 
Running zerver.tests.test_auth_backends.SocialAuthBase.test_user_cannot_log_into_wrong_subdomain
** Skipping zerver.tests.test_auth_backends.SocialAuthBase.test_user_cannot_log_into_wrong_subdomain: 
Running zerver.tests.test_auth_backends.SocialAuthBase.test_when_social_auth_subdomain_is_not_set
** Skipping zerver.tests.test_auth_backends.SocialAuthBase.test_when_social_auth_subdomain_is_not_set: 
Running zerver.tests.test_auth_backends.TestAdminSetBackends.test_change_enabled_backends
Running zerver.tests.test_auth_backends.TestAdminSetBackends.test_disable_all_backends
Running zerver.tests.test_auth_backends.TestAdminSetBackends.test_supported_backends_only_updated
Running zerver.tests.test_auth_backends.TestDevAuthBackend.test_choose_realm
Running zerver.tests.test_auth_backends.TestDevAuthBackend.test_choose_realm_with_subdomains_enabled
Running zerver.tests.test_auth_backends.TestDevAuthBackend.test_dev_direct_production_config_error
Running zerver.tests.test_auth_backends.TestDevAuthBackend.test_login_failure
Running zerver.tests.test_auth_backends.TestDevAuthBackend.test_login_failure_due_to_nonexistent_user
Running zerver.tests.test_auth_backends.TestDevAuthBackend.test_login_success
Running zerver.tests.test_auth_backends.TestDevAuthBackend.test_login_success_with_2fa
Running zerver.tests.test_auth_backends.TestDevAuthBackend.test_login_with_subdomain
Running zerver.tests.test_auth_backends.TestDevAuthBackend.test_redirect_to_next_url
Running zerver.tests.test_auth_backends.TestJWTLogin.test_login_failure_due_to_empty_subdomain
Running zerver.tests.test_auth_backends.TestJWTLogin.test_login_failure_due_to_wrong_subdomain
Running zerver.tests.test_auth_backends.TestJWTLogin.test_login_failure_when_bad_token_is_passed
Running zerver.tests.test_auth_backends.TestJWTLogin.test_login_failure_when_key_does_not_exist
Running zerver.tests.test_auth_backends.TestJWTLogin.test_login_failure_when_key_is_missing
Running zerver.tests.test_auth_backends.TestJWTLogin.test_login_failure_when_realm_is_missing
Running zerver.tests.test_auth_backends.TestJWTLogin.test_login_failure_when_user_does_not_exist
Running zerver.tests.test_auth_backends.TestJWTLogin.test_login_failure_when_user_is_missing
Running zerver.tests.test_auth_backends.TestJWTLogin.test_login_success
Running zerver.tests.test_auth_backends.TestJWTLogin.test_login_success_under_subdomains
Running zerver.tests.test_auth_backends.TestLDAP.test_dev_ldap_fail_login
Running zerver.tests.test_auth_backends.TestLDAP.test_email_and_ldap_backends_together
Running zerver.tests.test_auth_backends.TestLDAP.test_generate_dev_ldap_dir
Running zerver.tests.test_auth_backends.TestLDAP.test_get_or_build_user_email
Running zerver.tests.test_auth_backends.TestLDAP.test_get_or_build_user_when_ldap_has_no_email_attr
Running zerver.tests.test_auth_backends.TestLDAP.test_get_or_build_user_when_ldap_has_no_full_name_mapping
Running zerver.tests.test_auth_backends.TestLDAP.test_get_or_build_user_when_realm_is_deactivated
Running zerver.tests.test_auth_backends.TestLDAP.test_get_or_build_user_when_user_does_not_exist
Running zerver.tests.test_auth_backends.TestLDAP.test_get_or_build_user_when_user_exists
Running zerver.tests.test_auth_backends.TestLDAP.test_get_or_build_user_when_user_has_invalid_name
Running zerver.tests.test_auth_backends.TestLDAP.test_ldap_permissions
Running zerver.tests.test_auth_backends.TestLDAP.test_login_failure_due_to_deactivated_user
Running zerver.tests.test_auth_backends.TestLDAP.test_login_failure_due_to_nonexistent_user
2020-07-17 06:17:04.024 DEBG [zulip.ldap] ZulipLDAPAuthBackend: No ldap user matching django_to_ldap_username result: nonexistent. Input username: nonexistent@zulip.com
Running zerver.tests.test_auth_backends.TestLDAP.test_login_failure_due_to_wrong_password
Running zerver.tests.test_auth_backends.TestLDAP.test_login_failure_when_domain_does_not_match
2020-07-17 06:17:04.065 DEBG [zulip.ldap] ZulipLDAPAuthBackend: Email hamlet@zulip.com does not match LDAP domain acme.com.
Running zerver.tests.test_auth_backends.TestLDAP.test_login_success
Running zerver.tests.test_auth_backends.TestLDAP.test_login_success_when_user_does_not_exist_with_split_full_name_mapping
Running zerver.tests.test_auth_backends.TestLDAP.test_login_success_when_user_does_not_exist_with_valid_subdomain
Running zerver.tests.test_auth_backends.TestLDAP.test_login_success_with_different_subdomain
Running zerver.tests.test_auth_backends.TestLDAP.test_login_success_with_email_attr
Running zerver.tests.test_auth_backends.TestLDAP.test_login_success_with_username
Running zerver.tests.test_auth_backends.TestLDAP.test_login_success_with_valid_subdomain
Running zerver.tests.test_auth_backends.TestLDAP.test_user_email_from_ldapuser_with_append_domain
Running zerver.tests.test_auth_backends.TestMaybeSendToRegistration.test_sso_only_when_preregistration_user_does_not_exist
Running zerver.tests.test_auth_backends.TestMaybeSendToRegistration.test_sso_only_when_preregistration_user_exists
Running zerver.tests.test_auth_backends.TestPasswordAuthEnabled.test_password_auth_enabled_for_ldap
Running zerver.tests.test_auth_backends.TestQueryLDAP.test_ldap_not_configured
Running zerver.tests.test_auth_backends.TestQueryLDAP.test_normal_query
Running zerver.tests.test_auth_backends.TestQueryLDAP.test_query_email_attr
Running zerver.tests.test_auth_backends.TestQueryLDAP.test_user_not_present
Running zerver.tests.test_auth_backends.TestRequireEmailFormatUsernames.test_require_email_format_usernames_for_email_and_ldap_with_append_email
Running zerver.tests.test_auth_backends.TestRequireEmailFormatUsernames.test_require_email_format_usernames_for_email_and_ldap_with_email_attr
Running zerver.tests.test_auth_backends.TestRequireEmailFormatUsernames.test_require_email_format_usernames_for_email_only
Running zerver.tests.test_auth_backends.TestRequireEmailFormatUsernames.test_require_email_format_usernames_for_ldap_with_append_domain
Running zerver.tests.test_auth_backends.TestRequireEmailFormatUsernames.test_require_email_format_usernames_for_ldap_with_email_attr
Running zerver.tests.test_auth_backends.TestTwoFactor.test_direct_dev_login_with_2fa
Running zerver.tests.test_auth_backends.TestTwoFactor.test_two_factor_login_with_ldap
2020-07-17 06:17:04.939 INFO [two_factor.gateways.fake] Fake SMS to +12125550100: "Your token is: 123456"
Running zerver.tests.test_auth_backends.TestZulipAuthMixin.test_get_user
Running zerver.tests.test_auth_backends.TestZulipLDAPUserPopulator.test_authenticate
Running zerver.tests.test_auth_backends.TestZulipLDAPUserPopulator.test_deactivate_non_matching_users
Running zerver.tests.test_auth_backends.TestZulipLDAPUserPopulator.test_deactivate_user
2020-07-17 06:17:05.158 INFO [] Deactivating user hamlet@zulip.com because they are disabled in LDAP.
Running zerver.tests.test_auth_backends.TestZulipLDAPUserPopulator.test_dont_sync_disabled_ldap_user
2020-07-17 06:17:05.215 INFO [] Deactivating user hamlet@zulip.com because they are disabled in LDAP.
Running zerver.tests.test_auth_backends.TestZulipLDAPUserPopulator.test_ldaperror_doesnt_deactivate_user
Running zerver.tests.test_auth_backends.TestZulipLDAPUserPopulator.test_populate_user_returns_none
Running zerver.tests.test_auth_backends.TestZulipLDAPUserPopulator.test_reactivate_user
2020-07-17 06:17:05.536 INFO [] Reactivating user hamlet@zulip.com because they are not disabled in LDAP.
Running zerver.tests.test_auth_backends.TestZulipLDAPUserPopulator.test_same_full_name
Running zerver.tests.test_auth_backends.TestZulipLDAPUserPopulator.test_too_short_name
2020-07-17 06:17:05.605 WARN [django_auth_ldap] Name too short! while authenticating hamlet
Running zerver.tests.test_auth_backends.TestZulipLDAPUserPopulator.test_update_custom_profile_field
Running zerver.tests.test_auth_backends.TestZulipLDAPUserPopulator.test_update_custom_profile_field_invalid_data
2020-07-17 06:17:05.673 WARN [django_auth_ldap] Invalid data for birthday field: Birthday is not a date while authenticating hamlet
Running zerver.tests.test_auth_backends.TestZulipLDAPUserPopulator.test_update_custom_profile_field_no_mapping
Running zerver.tests.test_auth_backends.TestZulipLDAPUserPopulator.test_update_custom_profile_field_no_update
Running zerver.tests.test_auth_backends.TestZulipLDAPUserPopulator.test_update_custom_profile_field_not_present_in_ldap
2020-07-17 06:17:05.780 WARN [django_auth_ldap] uid=hamlet,ou=users,dc=zulip,dc=com does not have a value for the attribute nonExistantAttr
Running zerver.tests.test_auth_backends.TestZulipLDAPUserPopulator.test_update_full_name
Running zerver.tests.test_auth_backends.TestZulipLDAPUserPopulator.test_update_non_existent_profile_field
2020-07-17 06:17:05.845 WARN [django_auth_ldap] Custom profile field with name non_existent not found. while authenticating hamlet
Running zerver.tests.test_auth_backends.TestZulipLDAPUserPopulator.test_update_split_full_name
Running zerver.tests.test_auth_backends.TestZulipLDAPUserPopulator.test_update_user_avatar
Running zerver.tests.test_auth_backends.TestZulipLDAPUserPopulator.test_update_user_avatar_for_s3
Running zerver.tests.test_auth_backends.TestZulipLDAPUserPopulator.test_update_with_hidden_emails
Running zerver.tests.test_auth_backends.TestZulipLDAPUserPopulator.test_user_in_multiple_realms
Running zerver.tests.test_auth_backends.TestZulipLDAPUserPopulator.test_user_not_found_in_ldap
Running zerver.tests.test_auth_backends.TestZulipRemoteUserBackend.test_login_desktop_flow_otp_success_email
Running zerver.tests.test_auth_backends.TestZulipRemoteUserBackend.test_login_desktop_flow_otp_success_username
Running zerver.tests.test_auth_backends.TestZulipRemoteUserBackend.test_login_failure
Running zerver.tests.test_auth_backends.TestZulipRemoteUserBackend.test_login_failure_due_to_empty_subdomain
Running zerver.tests.test_auth_backends.TestZulipRemoteUserBackend.test_login_failure_due_to_invalid_email
Running zerver.tests.test_auth_backends.TestZulipRemoteUserBackend.test_login_failure_due_to_missing_field
Running zerver.tests.test_auth_backends.TestZulipRemoteUserBackend.test_login_failure_due_to_nonexisting_user
Running zerver.tests.test_auth_backends.TestZulipRemoteUserBackend.test_login_failure_due_to_wrong_subdomain
Running zerver.tests.test_auth_backends.TestZulipRemoteUserBackend.test_login_mobile_flow_otp_success_email
Running zerver.tests.test_auth_backends.TestZulipRemoteUserBackend.test_login_mobile_flow_otp_success_username
Running zerver.tests.test_auth_backends.TestZulipRemoteUserBackend.test_login_success
Running zerver.tests.test_auth_backends.TestZulipRemoteUserBackend.test_login_success_under_subdomains
Running zerver.tests.test_auth_backends.TestZulipRemoteUserBackend.test_login_success_with_sso_append_domain
Running zerver.tests.test_auth_backends.TestZulipRemoteUserBackend.test_redirect_to
Running zerver.tests.test_auth_backends.TestZulipRemoteUserBackend.test_start_remote_user_sso
Running zerver.tests.test_auth_backends.TestZulipRemoteUserBackend.test_start_remote_user_sso_with_desktop_app
